### ISSUE TITLE
Example showing the use of pyproject.toml file

### ISSUE THREAD

**Issue by achapkowski** [pypa/sample-namespace-packages#21]
Can namespace packages be created with pyproject.toml files only?  I couldn't find any references to these type of packages.

Thank you

**Comment by chrysle** [comment]
Of course you can replace _setup.py_ with _pyproject.toml_ in a namespace package.

This would have to include the following:

```toml
[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["example_pkg"]
namespaces = true

[project]
[...]
```
